export enum configEnum {
  DB_URL = 'DB_URL',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  LOG_ON = 'LOG_ON',
  PREFLIX = 'PREFLIX',
  CORS = 'CORS',
  VERSION = 'VERSION',
  REDIS_HOST = 'REDIS_URL',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  REDIS_NAME = 'REDIS_NAME',
}
